name: chatapp
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  firebase_storage: ^11.5.6
  flutter_bloc: ^8.1.3
  flutter_svg: ^2.0.9
  image_picker: ^1.0.5
  get_it: ^7.6.4
  equatable: ^2.0.5
  flutter_localizations:
    sdk: flutter
  intl: any
  cloud_firestore: ^4.13.6
  cached_network_image: ^3.3.0
  flutter_chat_bubble: ^2.0.2
  pinput: ^3.0.1
  intl_phone_number_input: ^0.7.4
  contacts_service: ^0.6.3
  permission_handler: ^11.1.0
  url_launcher: ^6.2.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  generate: true

  assets:
    - assets/icons/

  fonts:
    - family: Muli
      fonts:
        - asset: assets/fonts/muli/Muli.ttf
        - asset: assets/fonts/muli/Muli-Bold.ttf
          weight: 700
        - asset: assets/fonts/muli/Muli-Light.ttf
          weight: 300
