// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdc-_TGRY1JyxkW7IlzLbv487_Vr7BuEQ',
    appId: '1:1029623396547:web:21e0ce834669b514d68a76',
    messagingSenderId: '1029623396547',
    projectId: 'chatapp-dgswu8732',
    authDomain: 'chatapp-dgswu8732.firebaseapp.com',
    storageBucket: 'chatapp-dgswu8732.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAoW2TAGgmMC0CH7Cyx9mnzNCzWUCfvUm0',
    appId: '1:1029623396547:android:7c08afcc7250c191d68a76',
    messagingSenderId: '1029623396547',
    projectId: 'chatapp-dgswu8732',
    storageBucket: 'chatapp-dgswu8732.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2BLcKNxRp2r6nj-la0Ph3QwMu7SNIDUk',
    appId: '1:1029623396547:ios:d0f84e864e3c33aad68a76',
    messagingSenderId: '1029623396547',
    projectId: 'chatapp-dgswu8732',
    storageBucket: 'chatapp-dgswu8732.appspot.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2BLcKNxRp2r6nj-la0Ph3QwMu7SNIDUk',
    appId: '1:1029623396547:ios:438b83eee6f912bad68a76',
    messagingSenderId: '1029623396547',
    projectId: 'chatapp-dgswu8732',
    storageBucket: 'chatapp-dgswu8732.appspot.com',
    iosBundleId: 'com.example.chatapp.RunnerTests',
  );
}
